image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar app-ibank.jar -P:profile=test &
# запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)


build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true




